// This file is generated by generate_data.py.
// Do not edit it manually.

const cardSets = {
  "cvc": {
    name: "CVC Words",
    cards: [
      {
        word: "fox",
        rendering: "o",
        image: "images/fox.png"
      },
      {
        word: "cow",
        rendering: "o",
        image: "images/ou_cow.png"
      },
      {
        word: "pig",
        rendering: "i",
        image: "images/ou_ouch.png"
      },
      {
        word: "dog",
        rendering: "o",
        image: "images/ou_owl.png"
      },
      {
        word: "sun",
        rendering: "u",
        image: "images/ou_shout.png"
      }
    ]
  },
  "cvcc": {
    name: "CVCC Words",
    cards: [
      {
        word: "milk",
        rendering: "lk",
        image: "images/lk_milk.svg"
      },
      {
        word: "yolk",
        rendering: "lk",
        image: "images/yolk.png"
      },
      {
        word: "sulk",
        rendering: "lk",
        image: "images/sulk.png"
      },
      {
        word: "belt",
        rendering: "lt",
        image: "images/belt.png"
      },
      {
        word: "vest",
        rendering: "st",
        image: "images/vest.svg"
      },
      {
        word: "nest",
        rendering: "st",
        image: "images/nest2.png"
      },
      {
        word: "ant",
        rendering: "nt",
        image: "images/ant.png"
      },
      {
        word: "tent",
        rendering: "nt",
        image: "images/tent.png"
      },
      {
        word: "cart",
        rendering: "rt",
        image: "images/cart.png"
      },
      {
        word: "fork",
        rendering: "rk",
        image: "images/fork.png"
      },
      {
        word: "park",
        rendering: "rk",
        image: "images/park.png"
      },
      {
        word: "mask",
        rendering: "sk",
        image: "images/mask.png"
      },
      {
        word: "wasp",
        rendering: "sp",
        image: "images/wasp.png"
      },
      {
        word: "ink",
        rendering: "nk",
        image: "images/ink.png"
      },
      {
        word: "wink",
        rendering: "nk",
        image: "images/wink.png"
      },
      {
        word: "film",
        rendering: "lm",
        image: "images/film.png"
      },
      {
        word: "palm",
        rendering: "palm",
        image: "images/palm.png"
      },
      {
        word: "tusk",
        rendering: "sk",
        image: "images/tusk.png"
      }
    ]
  }
};
