// This file is generated by generate_data.py.
// Do not edit it manually.

const cardSets = {
  "cvc": {
    name: "CVC Words",
    cards: [
      {
        word: "cow",
        rendering: "o",
        image: "images/ou_cow.png"
      },
      {
        word: "pig",
        rendering: "i",
        image: "images/ou_ouch.png"
      },
      {
        word: "dog",
        rendering: "o",
        image: "images/ou_owl.png"
      },
      {
        word: "sun",
        rendering: "u",
        image: "images/ou_shout.png"
      }
    ]
  },
  "cvcc": {
    name: "CVCC Words",
    cards: [
      {
        word: "milk",
        rendering: "lk",
        image: "images/lk_milk.svg"
      },
      {
        word: "yolk",
        rendering: "lk",
        image: "images/yolk.svg"
      },
      {
        word: "belt",
        rendering: "lt",
        image: "images/belt.png"
      },
      {
        word: "vest",
        rendering: "st",
        image: "images/vest.svg"
      },
      {
        word: "nest",
        rendering: "st",
        image: "images/nest2.png"
      },
      {
        word: "photo",
        rendering: "ph",
        image: "images/ph_photo.png"
      }
    ]
  }
};
