// This file is generated by generate_data.py.
// Do not edit it manually.

const cardSets = {
  "cvc": {
    name: "CVC Words",
    cards: [
      {
        word: "cat",
        rendering: "a",
        image: "images/ou_cow.png"
      },
      {
        word: "pig",
        rendering: "i",
        image: "images/ou_ouch.png"
      },
      {
        word: "dog",
        rendering: "o",
        image: "images/ou_owl.png"
      },
      {
        word: "sun",
        rendering: "u",
        image: "images/ou_shout.png"
      }
    ]
  },
  "cvcc": {
    name: "CVCC Words",
    cards: [
      {
        word: "alphabet",
        rendering: "ph",
        image: "images/ph_alphabet.png"
      },
      {
        word: "elephant",
        rendering: "ph",
        image: "images/ph_elephant.png"
      },
      {
        word: "photo",
        rendering: "ph",
        image: "images/ph_photo.png"
      }
    ]
  }
};
