#!/usr/bin/env python3

"""
Generate data.js from a phonics cards JSON file.

Usage:
    ./generate_data.py cards.json

The JSON structure is:

{
  "cvc": {
    "name": "CVC Words",
    "cards": [
      {
        "word": "cat",
        "rendering": "a",
        "image": "cat.png"
      }
    ]
  }
}

Image paths are interpreted relative to the directory containing
the JSON file. They are written into data.js using forward slashes.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path


def fail(message: str) -> None:
    print(f"ERROR: {message}", file=sys.stderr)
    raise SystemExit(1)


def js_string(value: str) -> str:
    """Return a safely quoted JavaScript string."""
    return json.dumps(value, ensure_ascii=False)


def validate(data: object, json_dir: Path) -> None:
    if not isinstance(data, dict):
        fail("Top level of JSON must be an object containing card sets.")

    if not data:
        fail("JSON contains no card sets.")

    for set_id, card_set in data.items():
        if not isinstance(set_id, str) or not set_id:
            fail("Every card set must have a non-empty string ID.")

        if not isinstance(card_set, dict):
            fail(f"Set '{set_id}' must be an object.")

        name = card_set.get("name")
        cards = card_set.get("cards")

        if not isinstance(name, str) or not name.strip():
            fail(f"Set '{set_id}' must have a non-empty 'name'.")

        if not isinstance(cards, list):
            fail(f"Set '{set_id}' must have a 'cards' array.")

        if not cards:
            fail(f"Set '{set_id}' contains no cards.")

        for number, card in enumerate(cards, start=1):
            prefix = f"Set '{set_id}', card {number}"

            if not isinstance(card, dict):
                fail(f"{prefix} must be an object.")

            for field in ("word", "rendering", "image"):
                if field not in card:
                    fail(f"{prefix} is missing '{field}'.")

                if not isinstance(card[field], str) or not card[field].strip():
                    fail(f"{prefix} has an invalid '{field}'.")

            word = card["word"]
            rendering = card["rendering"]
            image = card["image"]

            if rendering not in word:
                fail(
                    f"{prefix}: rendering {rendering!r} "
                    f"does not occur in word {word!r}."
                )

            image_path = json_dir / image

            # if image_path.suffix.lower() != ".png":
            #     fail(
            #         f"{prefix}: image {image!r} is not a PNG file."
            #     )

            if not image_path.is_file():
                fail(
                    f"{prefix}: image file does not exist: "
                    f"{image_path}"
                )


def generate(data: dict, json_dir: Path) -> str:
    lines = [
        "// This file is generated by generate_data.py.",
        "// Do not edit it manually.",
        "",
        "const cardSets = {",
    ]

    set_items = list(data.items())

    for set_index, (set_id, card_set) in enumerate(set_items):
        lines.append(f"  {js_string(set_id)}: {{")
        lines.append(f"    name: {js_string(card_set['name'])},")
        lines.append("    cards: [")

        cards = card_set["cards"]

        for card_index, card in enumerate(cards):
            # Convert the image path to a browser-friendly relative path.
            image_path = (json_dir / card["image"]).resolve()

            try:
                image_path.relative_to(json_dir.resolve())
            except ValueError:
                fail(
                    f"Image for {card['word']!r} is outside the JSON directory."
                )

            # data.js is written to the current working directory, so the
            # image URL must be relative to data.js, not to cards.json.
            output_dir = Path.cwd().resolve()
            image_url = Path(
                __import__("os").path.relpath(image_path, output_dir)
            ).as_posix()

            comma = "," if card_index < len(cards) - 1 else ""

            lines.append("      {")
            lines.append(f"        word: {js_string(card['word'])},")
            lines.append(f"        rendering: {js_string(card['rendering'])},")
            lines.append(f"        image: {js_string(image_url)}")
            lines.append(f"      }}{comma}")

        lines.append("    ]")
        lines.append(f"  }}{',' if set_index < len(set_items) - 1 else ''}")

    lines.extend([
        "};",
        "",
    ])

    return "\n".join(lines)


def main() -> None:
    if len(sys.argv) != 2:
        print("Usage: ./generate_data.py cards.json", file=sys.stderr)
        raise SystemExit(2)

    json_file = Path(sys.argv[1]).resolve()

    if not json_file.is_file():
        fail(f"JSON file does not exist: {json_file}")

    if json_file.suffix.lower() != ".json":
        fail(f"Expected a .json file: {json_file}")

    try:
        data = json.loads(json_file.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        fail(f"Invalid JSON: {exc}")

    json_dir = json_file.parent

    validate(data, json_dir)

    output_file = Path("data.js").resolve()
    output_file.write_text(
        generate(data, json_dir),
        encoding="utf-8"
    )

    print(f"Generated {output_file}")
    print(f"Card sets: {len(data)}")
    print(f"Cards: {sum(len(s['cards']) for s in data.values())}")


if __name__ == "__main__":
    main()
